version: 1

environment:
  php: 8.1

pipeline:
  - name: Setup
    cmd: |
      composer install --no-interaction --prefer-dist --optimize-autoloader

  - name: Run Tests
    cmd: phpunit --exclude big
